name: 'Cache Warmup'
description: '🔥 Warm up caches of URLs located in XML sitemaps'
author: 'Elias Häußler'

branding:
  color: 'red'
  icon: 'trending-up'

inputs:
  version:
    description: 'Version of the cache-warmup library to use, defaults to "latest".'
    default: 'latest'
    required: true
  sitemaps:
    description: 'URLs or local filenames of XML sitemaps to be warmed up.'
    default: ''
  urls:
    description: 'Additional URLs to be warmed up.'
    default: ''
  limit:
    description: 'Limit the number of URLs to be processed.'
    default: '0'
  config:
    description: 'Path to an external configuration file.'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Check requirements'
      shell: 'bash'
      run: |
        ${GITHUB_ACTION_PATH}/bin/check_requirements.sh

    # @todo remove
#    - name: 'Download PHAR file'
#      id: 'download'
#      shell: 'bash'
#      run: |
#        ${GITHUB_ACTION_PATH}/bin/download_phar.sh \
#          "${{ inputs.version }}"

    - name: 'Pull Docker image'
      id: 'docker'
      shell: 'bash'
      run: |
        ${GITHUB_ACTION_PATH}/bin/pull_image.sh \
          "${{ inputs.version }}"

    - name: 'Verify config file'
      shell: 'bash'
      run: |
        ${GITHUB_ACTION_PATH}/bin/verify_config.sh \
          "${{ steps.docker.outputs.imageVersion }}" \
          "${{ inputs.config }}"

    - name: 'Run cache warmup'
      shell: 'bash'
      run: |
        ${GITHUB_ACTION_PATH}/bin/cache_warmup.sh \
          "${{ steps.docker.outputs.image }}" \
          "${{ inputs.sitemaps }}" \
          "${{ inputs.urls }}" \
          "${{ inputs.limit }}" \
          "${{ inputs.config }}"
