name: 'Cache Warmup'
description: '🔥 Warm up caches of URLs located in XML sitemaps'
author: 'Elias Häußler'

branding:
  color: 'red'
  icon: 'trending-up'

inputs:
  version:
    description: 'Version of the cache-warmup library to use, defaults to "latest".'
    default: 'latest'
    required: true
  sitemaps:
    description: 'URLs or local filenames of XML sitemaps to be warmed up.'
    default: ''
  urls:
    description: 'Additional URLs to be warmed up.'
    default: ''
  limit:
    description: 'Limit the number of URLs to be processed.'
    default: '0'
  config:
    description: 'Path to an external configuration file.'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Set up environment'
      uses: 'shivammathur/setup-php@v2'
      with:
        php-version: '8.3'
        coverage: 'none'

    - name: 'Run cache warmup'
      shell: 'bash'
      run: |
        ${GITHUB_ACTION_PATH}/src/main.sh \
          "${{ inputs.version }}" \
          "${{ inputs.sitemaps }}" \
          "${{ inputs.urls }}" \
          "${{ inputs.limit }}" \
          "${{ inputs.config }}"
