name: 'Cache Warmup'
description: '🔥 Warm up caches of URLs located in XML sitemaps'
author: 'Elias Häußler'

branding:
  color: 'red'
  icon: 'trending-up'

inputs:
  version:
    description: 'Version of the cache-warmup library to use, defaults to "latest".'
    default: 'latest'
    required: true
  sitemaps:
    description: 'URLs or local filenames of XML sitemaps to be warmed up.'
    default: ''
  urls:
    description: 'Additional URLs to be warmed up.'
    default: ''
  limit:
    description: 'Limit the number of URLs to be processed.'
    default: '0'
  progress:
    description: 'Show a progress bar during cache warmup.'
    default: ''
  verbosity:
    description: 'Increase output verbosity (v, vv or vvv).'
    default: ''
  config:
    description: 'Path to an external configuration file.'
    default: ''

outputs:
  version:
    description: 'Used version of the cache-warmup library'
    value: ${{ steps.cache-warmup.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 'Run cache warmup'
      id: 'cache-warmup'
      shell: 'bash'
      run: |
        ${GITHUB_ACTION_PATH}/bin/main.sh \
          "${{ inputs.version }}" \
          "${{ inputs.sitemaps }}" \
          "${{ inputs.urls }}" \
          "${{ inputs.limit }}" \
          "${{ inputs.progress }}" \
          "${{ inputs.verbosity }}" \
          "${{ inputs.config }}"
