name: CGL
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Linting
      - name: Lint shell files
        run: bash -c 'shopt -s globstar nullglob; shellcheck bin/*.sh'
