name: CGL
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 3 * * *'

jobs:
  prepare:
    name: Prepare workflow
    uses: eliashaeussler/.github/.github/workflows/pull-request.yaml@main

  cgl:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Linting
      - name: Lint shell files
        run: bash -c 'shopt -s globstar nullglob; shellcheck bin/*.sh'
