name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 3 * * *'

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@d35bc3755a6ea467539dd3d16ebe98a42b7f2f6e # 1.1.6

  repo-checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@d35bc3755a6ea467539dd3d16ebe98a42b7f2f6e # 1.1.6

  tests:
    name: 'Tests (${{ matrix.os }})'
    runs-on: ${{ matrix.os }}-latest

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        os: ["Ubuntu", "Windows", "macOS"]

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@d35bc3755a6ea467539dd3d16ebe98a42b7f2f6e # 1.1.6
        with:
          allowed-endpoints: |
            cache-warmup.dev:443

      - name: 'Set up stable environment'
        uses: eliashaeussler/gha/.github/actions/setup-php@d35bc3755a6ea467539dd3d16ebe98a42b7f2f6e # 1.1.6

      - name: 'Test: Sitemaps'
        id: sitemaps
        uses: $/
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml

      - name: 'Test: URLs'
        id: urls
        uses: $/
        with:
          urls: https://cache-warmup.dev/

      - name: 'Test: Limit'
        id: limit
        uses: $/
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Test: Progress'
        id: progress
        uses: $/
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          progress: true

      - name: 'Test: Verbosity level=1'
        id: verbosity-1
        uses: $/
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: v

      - name: 'Test: Verbosity level=2'
        id: verbosity-2
        uses: $/
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: vv

      - name: 'Test: Verbosity level=3'
        id: verbosity-3
        uses: $/
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: vvv

      - name: 'Test: Config file'
        id: config
        uses: $/
        with:
          config: tests/fixtures/cache-warmup.json
          limit: 10

      - name: 'Test: Config file and legacy version'
        id: config-legacy
        continue-on-error: true
        uses: $/
        with:
          version: 1.3.1
          config: tests/fixtures/cache-warmup.json
          limit: 10

      - name: 'Verify: Config file and legacy version'
        shell: bash
        env:
          TEST_CONFIG_LEGACY_OUTCOME: ${{ steps.config-legacy.outcome }}
        run: |
          if [ "$TEST_CONFIG_LEGACY_OUTCOME" != "failure" ]; then
            echo "::error title=Test with config file and legacy version: Invalid outcome::Expected \"failure\", got \"${TEST_CONFIG_LEGACY_OUTCOME}\"."
            exit 1
          fi

      - name: 'Test: Stable version'
        id: stable
        uses: $/
        env:
          # renovate: datasource=github-releases depName=eliashaeussler/cache-warmup
          CACHE_WARMUP_VERSION: '5.0.8'
        with:
          version: ${{ env.CACHE_WARMUP_VERSION }}
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Set up legacy environment'
        uses: eliashaeussler/gha/.github/actions/setup-php@d35bc3755a6ea467539dd3d16ebe98a42b7f2f6e # 1.1.6
        with:
          php-version: 8.1 # renovate-ignore

      - name: 'Test: Legacy version'
        id: legacy
        uses: $/
        with:
          version: 1.3.1
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Verify: Legacy version'
        shell: bash
        env:
          TEST_LEGACY_VERSION_OUTPUT: ${{ steps.legacy.outputs.version }}
        run: |
          if [ "$TEST_LEGACY_VERSION_OUTPUT" != "1.3.1" ]; then
            echo "::error title=Test with legacy version: Invalid output::Expected \"1.3.1\" as output \"version\", got \"${TEST_LEGACY_VERSION_OUTPUT}\"."
            exit 1
          fi

      - name: 'Test: Lowest version'
        id: lowest
        uses: $/
        with:
          version: 0.7.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Test: Lowest signed version'
        id: lowest-signed
        uses: $/
        with:
          version: 0.7.6
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Test: Unsupported version'
        id: unsupported
        continue-on-error: true
        uses: $/
        with:
          version: 0.1.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Verify: Unsupported version'
        shell: bash
        env:
          TEST_UNSUPPORTED_OUTCOME: ${{ steps.unsupported.outcome }}
        run: |
          if [ "$TEST_UNSUPPORTED_OUTCOME" != "failure" ]; then
            echo "::error title=Test with unsupported version: Invalid outcome::Expected \"failure\", got \"${TEST_UNSUPPORTED_OUTCOME}\"."
            exit 1
          fi
