name: Tests
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["Ubuntu", "Windows", "macOS"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up stable environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Test with sitemaps
        id: sitemaps
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml

      - name: Test with URLs
        id: urls
        uses: ./
        with:
          urls: https://cache-warmup.dev/

      - name: Test with limit
        id: limit
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Test with progress
        id: progress
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          progress: true

      - name: Test with verbosity level=1
        id: verbosity-1
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: v

      - name: Test with verbosity level=2
        id: verbosity-2
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: vv

      - name: Test with verbosity level=3
        id: verbosity-3
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: vvv

      - name: Test with config file
        id: config
        uses: ./
        with:
          config: tests/fixtures/cache-warmup.json
          limit: 10

      - name: Test with config file and legacy version
        id: config-legacy
        continue-on-error: true
        uses: ./
        with:
          version: 2.6.0
          config: tests/fixtures/cache-warmup.json
          limit: 10

      - name: Test with stable version
        id: stable
        uses: ./
        env:
          # renovate: datasource=github-releases depName=eliashaeussler/cache-warmup
          CACHE_WARMUP_VERSION: '3.1.0'
        with:
          version: $CACHE_WARMUP_VERSION
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Test with legacy version
        id: legacy
        uses: ./
        with:
          version: 2.6.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Set up lowest environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Test with lowest version
        id: lowest
        uses: ./
        with:
          version: 0.7.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Test with lowest signed version
        id: lowest-signed
        uses: ./
        with:
          version: 0.7.6
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Test with unsupported version
        id: unsupported
        continue-on-error: true
        uses: ./
        with:
          version: 0.1.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Test outputs
        id: outputs
        shell: 'bash'
        run: |
          if [ "${{ steps.legacy.outputs.version }}" != "2.6.0" ]; then
            echo "::error title=Invalid output::Expected \"2.6.0\" as output \"version\", got \"${{ steps.legacy.outputs.version }}\"."
            exit 1
          fi
