name: Tests
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 3 * * *'

jobs:
  tests:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["Ubuntu", "Windows", "macOS"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up stable environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: 'Test: Sitemaps'
        id: sitemaps
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml

      - name: 'Test: URLs'
        id: urls
        uses: ./
        with:
          urls: https://cache-warmup.dev/

      - name: 'Test: Limit'
        id: limit
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Test: Progress'
        id: progress
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          progress: true

      - name: 'Test: Verbosity level=1'
        id: verbosity-1
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: v

      - name: 'Test: Verbosity level=2'
        id: verbosity-2
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: vv

      - name: 'Test: Verbosity level=3'
        id: verbosity-3
        uses: ./
        with:
          sitemaps: https://cache-warmup.dev/sitemap.xml
          verbosity: vvv

      - name: 'Test: Config file'
        id: config
        uses: ./
        with:
          config: tests/fixtures/cache-warmup.json
          limit: 10

      - name: 'Test: Config file and legacy version'
        id: config-legacy
        continue-on-error: true
        uses: ./
        with:
          version: 1.3.1
          config: tests/fixtures/cache-warmup.json
          limit: 10
      - name: 'Verify: Config file and legacy version'
        shell: bash
        run: |
          if [ "${{ steps.config-legacy.outcome }}" != "failure" ]; then
            echo "::error title=Test with config file and legacy version: Invalid outcome::Expected \"failure\", got \"${{ steps.config-legacy.outcome }}\"."
            exit 1
          fi

      - name: 'Test: Stable version'
        id: stable
        uses: ./
        env:
          # renovate: datasource=github-releases depName=eliashaeussler/cache-warmup
          CACHE_WARMUP_VERSION: '4.1.0'
        with:
          version: $CACHE_WARMUP_VERSION
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: Set up legacy environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: 'Test: Legacy version'
        id: legacy
        uses: ./
        with:
          version: 1.3.1
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10
      - name: 'Verify: Legacy version'
        shell: bash
        run: |
          if [ "${{ steps.legacy.outputs.version }}" != "1.3.1" ]; then
            echo "::error title=Test with legacy version: Invalid output::Expected \"1.3.1\" as output \"version\", got \"${{ steps.legacy.outputs.version }}\"."
            exit 1
          fi

      - name: 'Test: Lowest version'
        id: lowest
        uses: ./
        with:
          version: 0.7.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Test: Lowest signed version'
        id: lowest-signed
        uses: ./
        with:
          version: 0.7.6
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10

      - name: 'Test: Unsupported version'
        id: unsupported
        continue-on-error: true
        uses: ./
        with:
          version: 0.1.0
          sitemaps: https://cache-warmup.dev/sitemap.xml
          limit: 10
      - name: 'Verify: Unsupported version'
        shell: bash
        run: |
          if [ "${{ steps.unsupported.outcome }}" != "failure" ]; then
            echo "::error title=Test with unsupported version: Invalid outcome::Expected \"failure\", got \"${{ steps.unsupported.outcome }}\"."
            exit 1
          fi
